name: CI of pitstop-workshop-planning microservice
#Déclencher le pipline si une modification fait dans le pitstop-express-gateway microservice
on:
  push:
    paths:
      - 'pitstop-workshop-planning/**'
  workflow_dispatch:


jobs:
  build:
    # Ensure the runner is using the latest Ubuntu version

    runs-on: ubuntu-latest  

    steps:
      - name: "Checkout the code to the runner"
        uses: actions/checkout@v4

      - name: "Build Docker image"
        run: |
          cd  pitstop-workshop-planning
          docker build -t  ${{secrets.DOCKER_USERNAME }}/pitstop-workshop-planning .
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push the image to Docker Hub"
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pitstop-workshop-planning
